### ISSUE TITLE
Issues with generation of REVINFO table

### ISSUE THREAD

**Issue by ishaoke94** [sdoxsee/jhipster-app-envers#1]
I've been trying to audit my data using envers in Jhipster on Eclipse. I've been getting errors with generation of REVINFO table and hence its not processing the SQL query. How can this issue be solved?

**Comment by sdoxsee** [comment]
have you followed the steps at http://stackoverflow.com/questions/29290519/how-to-use-jhipster-and-hibernate-envers/29308586#29308586? I've also updated the project as there were some fixes I needed to add. Let me know how it goes.

**Comment by ishaoke94** [comment]
I followed those steps and have a few questions:
1. ```
     While adding ‘repositoryFactoryBeanClass=org.springframework.data.envers.repository.support.EnversRevisionRepositoryFactoryBean.class’ to the @EnableJpaRepositories annotation, do we delete what the annotation has already in the parentheses?
   ```
2. ```
     How and where do we add the CustomRevisionEntity and the CustomRevisionListener? Do you have code for that?
   ```
3. ```
     Where is master.xml?
   ```

From: Stephen Doxsee [mailto:notifications@github.com]
Sent: 15 June 2015 18:55
To: sdoxsee/jhipster-app-envers
Cc: Oke, Isha: IT (PUN)
Subject: Re: [jhipster-app-envers] Issues with generation of REVINFO table (#1)

have you followed the steps at http://stackoverflow.com/questions/29290519/how-to-use-jhipster-and-hibernate-envers/29308586#29308586? I've also updated the project as there were some fixes I needed to add. Let me know how it goes.

—
Reply to this email directly or view it on GitHubhttps://github.com/sdoxsee/jhipster-app-envers/issues/1#issuecomment-112069041.

---

This message is for information purposes only, it is not a recommendation, advice, offer or solicitation to buy or sell a product or service nor an official confirmation of any transaction. It is directed at persons who are professionals and is not intended for retail customer use. Intended for recipient only. This message is subject to the terms at: www.barclays.com/emaildisclaimer.

For important disclosures, please see: www.barclays.com/salesandtradingdisclaimer regarding market commentary from Barclays Sales and/or Trading, who are active market participants; and in respect of Barclays Research, including disclosures relating to specific issuers, please see http://publicresearch.barclays.com.

---

**Comment by sdoxsee** [comment]
Closing this as this is not an issue.

For 1, please see the updated stackoverflow answer (or see DatabaseConfiguration.java in this github project).
For 2 and 3, please find the files in the github source of this project and do something similar.

Hope you can get it going.
